import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";
import type { DeckContent } from "./gemini";
import { hexToRgb01, type DeckTheme, type DeckFont } from "./themes";

const PAGE_W = 960; // 13.33in
const PAGE_H = 540; // 7.5in

// StandardFonts use WinAnsi encoding, which cannot render smart quotes, the
// rupee sign, bullets, etc. Normalise text to a safe subset.
function sanitize(s: string): string {
  return String(s || "")
    .replace(/₹/g, "Rs.")
    .replace(/[‘’‚‛]/g, "'")
    .replace(/[“”„]/g, '"')
    .replace(/[–—]/g, "-")
    .replace(/•/g, "-")
    .replace(/…/g, "...")
    // drop anything remaining outside basic printable Latin-1
    .replace(/[^\x20-\x7E\xA0-\xFF]/g, "");
}

function wrap(text: string, font: PDFFont, size: number, maxW: number): string[] {
  const words = sanitize(text).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (font.widthOfTextAtSize(test, size) > maxW && line) {
      lines.push(line);
      line = w;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function renderPdf(
  deck: DeckContent,
  theme: DeckTheme,
  font: DeckFont,
  founderName: string
): Promise<string> {
  const doc = await PDFDocument.create();
  doc.setTitle(`${deck.companyName} Pitch Deck`);
  doc.setAuthor("FounderStreet");

  const head = await doc.embedFont(StandardFonts[font.pdfHead]);
  const body = await doc.embedFont(StandardFonts[font.pdfBody]);

  const accent = hexToRgb01(theme.accent);
  const dark = hexToRgb01(theme.dark);
  const light = hexToRgb01(theme.light);
  const ink = hexToRgb01(theme.ink);
  const muted = hexToRgb01(theme.muted);
  const C = (c: { r: number; g: number; b: number }) => rgb(c.r, c.g, c.b);

  // ── Cover ───────────────────────────────────────────────
  const cover = doc.addPage([PAGE_W, PAGE_H]);
  cover.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: C(dark) });
  cover.drawRectangle({ x: 64, y: 330, width: 70, height: 8, color: C(accent) });
  wrap(deck.companyName, head, 44, PAGE_W - 128).slice(0, 3).forEach((ln, i) => {
    cover.drawText(ln, { x: 64, y: 285 - i * 52, size: 44, font: head, color: rgb(1, 1, 1) });
  });
  if (deck.tagline) {
    wrap(deck.tagline, body, 18, PAGE_W - 128).slice(0, 2).forEach((ln, i) => {
      cover.drawText(ln, { x: 64, y: 150 - i * 24, size: 18, font: body, color: C(accent) });
    });
  }
  cover.drawText(sanitize(founderName ? `Prepared for ${founderName}` : "Investor Pitch Deck"), {
    x: 64, y: 48, size: 11, font: body, color: rgb(1, 1, 1), opacity: 0.6,
  });
  cover.drawText("Generated by FounderStreet", {
    x: PAGE_W - 64 - body.widthOfTextAtSize("Generated by FounderStreet", 10), y: 48, size: 10, font: body, color: rgb(1, 1, 1), opacity: 0.5,
  });

  // ── Content slides ─────────────────────────────────────
  const content = deck.slides.filter((_, i) => i > 0);
  content.forEach((slide, idx) => {
    const p = doc.addPage([PAGE_W, PAGE_H]);
    p.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: C(light) });
    p.drawRectangle({ x: 0, y: 0, width: 16, height: PAGE_H, color: C(accent) });

    p.drawText(String(idx + 1).padStart(2, "0"), { x: 56, y: PAGE_H - 60, size: 13, font: body, color: C(accent) });

    let y = PAGE_H - 108;
    wrap(slide.title, head, 30, PAGE_W - 130).slice(0, 2).forEach((ln) => {
      p.drawText(ln, { x: 56, y, size: 30, font: head, color: C(ink) });
      y -= 38;
    });
    if (slide.subtitle) {
      y -= 4;
      wrap(slide.subtitle, body, 14, PAGE_W - 130).slice(0, 2).forEach((ln) => {
        p.drawText(ln, { x: 56, y, size: 14, font: body, color: C(muted) });
        y -= 20;
      });
    }
    y -= 22;
    for (const b of (slide.bullets || []).filter(Boolean)) {
      const lines = wrap(b, body, 15, PAGE_W - 160);
      p.drawRectangle({ x: 58, y: y + 5, width: 6, height: 6, color: C(accent) });
      lines.forEach((ln) => {
        p.drawText(ln, { x: 78, y, size: 15, font: body, color: C(ink) });
        y -= 22;
      });
      y -= 8;
      if (y < 60) return;
    }

    p.drawText(sanitize(`${deck.companyName}  |  FounderStreet`), { x: 56, y: 32, size: 10, font: body, color: C(muted) });
  });

  const bytes = await doc.save();
  return Buffer.from(bytes).toString("base64");
}
