import pptxgen from "pptxgenjs";
import type { DeckContent } from "./gemini";
import type { DeckTheme, DeckFont } from "./themes";

// Builds an editable .pptx and returns it as a base64 string.
export async function renderPptx(
  deck: DeckContent,
  theme: DeckTheme,
  font: DeckFont,
  founderName: string
): Promise<string> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE"; // 13.33 x 7.5 in
  pptx.author = "FounderStreet";
  pptx.company = "FounderStreet";
  pptx.title = `${deck.companyName} Pitch Deck`;

  const W = 13.33;
  const H = 7.5;

  // ── Cover ───────────────────────────────────────────────
  const cover = pptx.addSlide();
  cover.background = { color: theme.dark };
  cover.addShape(pptx.ShapeType.rect, { x: 0.9, y: 2.5, w: 1.1, h: 0.14, fill: { color: theme.accent } });
  cover.addText(deck.companyName, {
    x: 0.9, y: 2.8, w: W - 1.8, h: 1.6,
    fontFace: font.pptHead, fontSize: 48, bold: true, color: "FFFFFF", align: "left",
  });
  if (deck.tagline) {
    cover.addText(deck.tagline, {
      x: 0.9, y: 4.35, w: W - 1.8, h: 0.8,
      fontFace: font.pptBody, fontSize: 20, color: theme.accent, align: "left",
    });
  }
  cover.addText(founderName ? `Prepared for ${founderName}` : "Investor Pitch Deck", {
    x: 0.9, y: 6.5, w: W - 1.8, h: 0.4,
    fontFace: font.pptBody, fontSize: 12, color: "FFFFFF", transparency: 40, align: "left",
  });
  cover.addText("Generated by FounderStreet", {
    x: W - 4.4, y: 6.5, w: 3.5, h: 0.4,
    fontFace: font.pptBody, fontSize: 11, color: "FFFFFF", transparency: 55, align: "right",
  });

  // ── Content slides ─────────────────────────────────────
  const content = deck.slides.filter((_, i) => i > 0); // slide 0 is the cover concept
  content.forEach((slide, idx) => {
    const s = pptx.addSlide();
    s.background = { color: theme.light };
    // left accent bar
    s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.22, h: H, fill: { color: theme.accent } });
    // number chip
    s.addText(String(idx + 1).padStart(2, "0"), {
      x: 0.7, y: 0.6, w: 1, h: 0.5, fontFace: font.pptBody, fontSize: 13, bold: true, color: theme.accent, align: "left",
    });
    // title
    s.addText(slide.title, {
      x: 0.7, y: 1.0, w: W - 1.4, h: 1.0,
      fontFace: font.pptHead, fontSize: 30, bold: true, color: theme.ink, align: "left",
    });
    if (slide.subtitle) {
      s.addText(slide.subtitle, {
        x: 0.7, y: 1.95, w: W - 1.4, h: 0.6,
        fontFace: font.pptBody, fontSize: 15, color: theme.muted, align: "left", italic: true,
      });
    }
    const bullets = (slide.bullets || []).filter(Boolean);
    if (bullets.length) {
      s.addText(
        bullets.map((b) => ({ text: b, options: { bullet: { code: "2022", indent: 18 }, color: theme.ink, fontSize: 17, fontFace: font.pptBody, paraSpaceAfter: 12 } })),
        { x: 0.75, y: slide.subtitle ? 2.8 : 2.4, w: W - 1.6, h: H - 3.4, align: "left", valign: "top" }
      );
    }
    // footer
    s.addText(`${deck.companyName}  ·  FounderStreet`, {
      x: 0.7, y: H - 0.55, w: W - 1.4, h: 0.35,
      fontFace: font.pptBody, fontSize: 10, color: theme.muted, align: "left",
    });
  });

  return (await pptx.write({ outputType: "base64" })) as string;
}
